//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food_Items
    {
        public int id { get; set; }
        public string Food_Name { get; set; }
        public string Ingrediants { get; set; }
        public string Special_Notes { get; set; }
        public string Catageory { get; set; }
        public Nullable<int> Price { get; set; }
    }
}
