//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KitchenProjectEntities : DbContext
    {
        public KitchenProjectEntities()
            : base("name=KitchenProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<User_Credentials> User_Credentials { get; set; }
        public DbSet<Admin_Credentials> Admin_Credentials { get; set; }
        public DbSet<Food_Items> Food_Items { get; set; }
        public DbSet<cart> carts { get; set; }
    }
}
